# Generated by Django 5.2.12 on 2026-03-15 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_update_accountsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsubmission',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
